# 7-11 closure rule
# Deguerry, F., Pastore, L., Wu, S., Clark, A., Chappell, J., & Schalk, M. (2006). The diverse sesquiterpene profile of patchouli, Pogostemon cablin, is correlated with a limited number of sesquiterpene synthases. Archives of Biochemistry and Biophysics, 454(2), 123–136. https://doi.org/10.1016/j.abb.2006.08.006

rule [
 ruleID "7-11 closure"
left [
        node [ id 11 label "C+" ]
        edge [ source  6 target  7 label "=" ]
        node [ id  6 label "C" ]
    ]
    context [
        node [ id  1 label "C" ]
        node [ id  2 label "C" ]
        node [ id  3 label "C" ]
        node [ id  4 label "C" ]
        node [ id  5 label "C" ]
        node [ id  7 label "C" ]
        node [ id  8 label "C" ]
        node [ id  9 label "C" ]
        node [ id 10 label "C" ]
        node [ id 12 label "C" ]
        node [ id 13 label "C" ]
        node [ id 14 label "C" ]
        node [ id 15 label "C" ]
        edge [ source  1 target  2 label "*" ]
        edge [ source  2 target  3 label "=" ]
        edge [ source  3 target  4 label "*" ]
        edge [ source  3 target 15 label "*" ]
        edge [ source  4 target  5 label "*" ]
        edge [ source  5 target  6 label "*" ]
        edge [ source  7 target  8 label "*" ]
        edge [ source  7 target 14 label "*" ]
        edge [ source  8 target  9 label "*" ]
        edge [ source  9 target 10 label "*" ]
        edge [ source 10 target 11 label "*" ]
        edge [ source 10 target  1 label "*" ]
        edge [ source 11 target 12 label "*" ]
        edge [ source 11 target 13 label "*" ]
    ]
    right [
        node [ id 11 label "C" ]
        edge [ source  6 target  7 label "-" ]
        edge [ source 11 target  7 label "-" ]
        node [ id  6 label "C+" ]
    ]
]