#   Takeda, K. (1974). Stereospecific cope rearrangement of the germacrene-type sesquiterpenes. Tetrahedron, 30(12), 1525–1534. https://doi.org/10.1016/S0040-4020(01)90674-X
#   Colby, S. M., Crock, J., Dowdle-Rizzo, B., Lemaux, P. G., & Croteau, R. (1998). Germacrene C synthase from Lycopersicon esculentum cv. VFNT cherry tomato: cDNA isolation, characterization, and bacterial expression of the multiple product sesquiterpene cyclase. Proceedings of the National Academy of Sciences of the United States of America, 95(5), 2216–2221. https://doi.org/10.1073/pnas.95.5.2216
rule [
 ruleID "Cope Rearrangment 01"
 left [
  edge [ source  2 target  3 label "=" ]
  edge [ source  3 target  4 label "-" ]
  edge [ source  4 target  5 label "-" ]
  edge [ source  5 target  6 label "-" ]
  edge [ source  6 target  7 label "=" ]
 ]
 context [
  node [ id  1 label "C" ]
  node [ id  2 label "C" ]
  node [ id  3 label "C" ]
  node [ id  4 label "C" ]
  node [ id  5 label "C" ]
  node [ id  6 label "C" ]
  node [ id  7 label "C" ]
  node [ id  8 label "C" ]
  node [ id  9 label "C" ]
  node [ id 10 label "C" ]
  node [ id 11 label "C" ]
  node [ id 12 label "C" ]
  node [ id 13 label "C" ]
  node [ id 14 label "C" ]
  node [ id 15 label "C" ]
  edge [ source  1 target  2 label "-" ]
  edge [ source  1 target 10 label "*" ]
  edge [ source  8 target  9 label "*" ]
  edge [ source  7 target  8 label "-" ]
  edge [ source  7 target 14 label "-" ]
  edge [ source  3 target 15 label "*" ]
  edge [ source  9 target 10 label "-" ]
  edge [ source  10 target 11 label "*" ]
  edge [ source  11 target 12 label "*" ]
  edge [ source  11 target 13 label "*" ]
 ]
 right [
  edge [ source  2 target  3 label "-" ]
  edge [ source  2 target  7 label "-" ]
  edge [ source  3 target  4 label "=" ]
  edge [ source  5 target  6 label "=" ]
  edge [ source  6 target  7 label "-" ]
 ]
]